- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create a new Route
      k8s:
        state: present
        resource_definition: |
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            name: helloworld
            namespace: pipeline-tutorial
          spec:
            host: helloworld-pipeline-tutorial.apps.devocpcluster.imdevocplab.com
            to:
              kind: Service
              name: helloworld
              weight: 100
            port:
              targetPort: 8080
            wildcardPolicy: None
        wait: yes
      register: helloworld_route
    - name: Get the Route
      k8s_info:
        kind: Route
        namespace: pipeline-tutorial
      register: funstuff_route_list
    - name: Log Route Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{funstuff_route_list.resources}}'
      loop_control:
        label: "Route (Namespace: {{item | json_query('metadata.namespace')}})"
