- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create a new deployment
      k8s:
        state: present
        resource_definition: |
          apiVersion: apps.openshift.io/v1
          kind: DeploymentConfig
          metadata:
            labels:
              app: pipelines-vote-ui-dev
            name: pipelines-vote-ui-dev
          spec:
            selector:
              name: pipelines-vote-ui-dev
            template:
              metadata:
                labels:
                  name: "pipelines-vote-ui-dev"
              spec:
                containers:
                  - image: quay.io/openshift-pipeline/vote-ui-dev:latest
                    imagePullPolicy: Always
                    name: pipelines-vote-ui-dev
                    ports:
                      - containerPort: 8080
                        protocol: TCP
                      - containerPort: 9090
                        protocol: TCP
                    env:
                      - name: VOTING_API_SERVICE_HOST
                        value: pipelines-vote-api
                      - name: VOTING_API_SERVICE_PORT
                        value: "9000"
            replicas: 1
            strategy:
              type: "Rolling"
            paused: false
            revisionHistoryLimit: 2
            minReadySeconds: 0

        wait: yes
      register: vote_ui_dev_deployment
    - name: Get the Deployment
      k8s_info:
        kind: DeploymentConfig
        namespace: pipeline-tutorial
      register: funstuff_deployments_list
    - name: Log Deployment Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: "{{funstuff_deployments_list.resources}}"
      loop_control:
        label: "Deployment (Namespace: {{item | json_query('metadata.namespace')}},Replicas:{{ item | json_query('spec.replicas')}})"
